services:
  laravel-docker:
    volumes:
      - ./ouest-camions-api/storage:/var/www/app/storage:rw
    command: >
      sh -c "chown -R www-data:www-data /var/www/app/storage &&
             chmod -R 775 /var/www/app/storage &&
             apache2-foreground"

  test-api:
    environment:
      BASE_URL: http://laravel-docker:80
      JWT_SECRET: At4oMJgeieryAyYyPO2oXA22ZI6sQIlt7KwlSxxwmr1T5cZOn2N1aP6H9YZskLAG
    command: >
      sh -c "npm ci && npx jest --runInBand"