services:
  laravel-docker:
    container_name: laravel-docker
    build: ./ouest-camions-api # back
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./ouest-camions-api/storage:/var/www/app/storage
  # - /c/wamp64/www/ouestcamions/ouest-camions-api/storage:/var/www/app/storage

  vue-docker:
    container_name: vue-docker
    build: ./ouest-camions-react #front
    ports:
      - 80:80
    restart: unless-stopped

  mysql_db:
    image: mysql:latest
    container_name: mysql_db 
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_DATABASE: ouest_camions_test # base test
    ports:
      - 3306:3306
    volumes :
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  mysql_data: