services:
  laravel-docker:
    container_name: laravel-docker
    build: ./ouest-camions-api # back
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
    - ./ouest-camions-api/storage:/var/www/app/storage:rw
    depends_on:
      mysql_db:
        condition: service_healthy
    command: >
      sh -c "chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap/cache &&
             chmod -R 775 /var/www/app/storage /var/www/app/bootstrap/cache &&
             apache2-foreground"
  vue-docker:
    container_name: vue-docker
    build: ./ouest-camions-react #front
    ports:
      - 80:80
    restart: unless-stopped

  mysql_db:
    image: mysql:latest
    container_name: mysql_db 
    environment:
      MYSQL_ROOT_PASSWORD: histo44 
      MYSQL_DATABASE: ouest_camions_test # base test
    ports:
      - 3306:3306
    volumes :
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  test-api:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./test-api:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
    - laravel-docker
    command: >
      sh -c "npm install && npx jest --runInBand"

volumes:
  mysql_data:
