name: ouest-camions

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "dev" # branch of github 
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-api # my testfile 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1 # go to github
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Database migrate
      run: docker exec laravel-docker bash -c "php artisan migrate"
    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: install Jest
      run: npm install -g jest # global 
    - name: Run tests
      run: npm run test